### ISSUE TITLE
если выключен антиалиасинг, у некоторых размеров наклонные линии утолщены

### ISSUE THREAD

**Issue by volth** [wholemy/fonts#1]
Например 16 более-менее хорошо: http://i.imgur.com/zEGKkCg.png
![](http://i.imgur.com/zEGKkCg.png)

У 12 заглавные буквы: http://i.imgur.com/rX39wG8.png
![](http://i.imgur.com/rX39wG8.png)

У 20 строчные буквы: http://i.imgur.com/1UVpGue.png
![](http://i.imgur.com/1UVpGue.png)

(гитхаб сглаживает картинки, лучше смотреть по прямым ссылкам на imgur)

**Comment by wholemy** [comment]
Да, мне известна эта проблема, но эти шрифты как раз рассчитаны именно на обратную стадию, я мог бы еще больше примеров показать, но я не буду поддерживать этот режим, я добивался идеала для ClearType-Ideal-Animated) Я не смогу уменьшить толщину линий или их наклон, во первых они точно выверены по ширине, это наверняка сам механизм так их представляет) Буква X не имеет дополнительного наклона, наклон не очень точный у буквы N, V и К, английских, в угоду того чтобы закорючки не бросались в глаза, у М центральные линии сдвинуты вверх, но даже если бы я их не сдвигал, они выглядели бы как и у буквы Х) Я бы сказал так, то что эти шрифты так хорошо выглядят без сглаживания уже достижение) Но они рассчитаны именно на сглаживание) Большинство координат было установлено в ручную и они имеют высокую точность) Вы можете взять редактор FontForge и самостоятельно убедится в точности линий, создать горизонтальную или вертикальную линию, повернуть её на 45 градусов и убедится, что механизм его отрисует так же)
